### PR TITLE
Updating minimum sphinx version in setup.py

### LINKED ISSUE #210: AttributeError: 'module' object has no attribute 'getLogger'
We just pulled in a new version of numpydoc and our CI started breaking everywhere with
```
00:00:52.522 + sphinx-build -M html docs docs/_build
00:00:53.001 Running Sphinx v1.5.6
00:00:53.001 making output directory...
00:00:53.864 
00:00:53.864 Exception occurred:
00:00:53.865   File "/home/jenkins-slave/virtualenvs/executor-0/autotest-builder/local/lib/python2.7/site-packages/numpydoc/numpydoc.py", line 44, in <module>
00:00:53.865     logger = logging.getLogger(__name__)
00:00:53.865 AttributeError: 'module' object has no attribute 'getLogger'
00:00:53.866 The full traceback has been saved in /tmp/sphinx-err-Gw1CKi.log, if you want to report the issue to the developers.
00:00:53.866 Please also report this if it was a user error, so that a better error message can be provided next time.
00:00:53.866 A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

This does not appear to be a Sphinx issue, but rather an issue with the latest numpydoc.

### PR DESCRIPTION
**Pull request by bsipocz**
Fixes #210 

I'm seeing the `getLogger` error message in our CI but then in `setup.py` the fact that it should work with 1.2.3 has sent me into some dead-ends.

```
    logger = logging.getLogger(__name__)
AttributeError: module 'sphinx.util.logging' has no attribute 'getLogger'
```

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @bsipocz. I just updated it to 1.6.5 to match our CI and have a full version number. 

Waiting for a decision on gh-210, then I'll either put this or another fix in and release 0.9.1 later today.

**Comment by jnothman** [comment]
Thanks @bsipocz
